[build-system]
requires = ["setuptools>=61.0", "catkin_pkg"]
build-backend = "setuptools.build_meta"

[project]
name = "rt-gene"
version = "4.0.1"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["rt_gene", "rt_bene"]
package-dir = {"" = "src"}